# permissions to do viewer clusterenforcers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterenforcer-viewer-role
rules:
- apiGroups:
  - rode.liatr.io
  resources:
  - clusterenforcers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rode.liatr.io
  resources:
  - clusterenforcers/status
  verbs:
  - get
