# permissions to do edit clusterenforcers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusterenforcer-editor-role
rules:
- apiGroups:
  - rode.liatr.io
  resources:
  - clusterenforcers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rode.liatr.io
  resources:
  - clusterenforcers/status
  verbs:
  - get
  - patch
  - update
