
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: rode-manager-role
rules:
- apiGroups:
  - rode.liatr.io
  resources:
  - attesters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rode.liatr.io
  resources:
  - attesters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rode.liatr.io
  resources:
  - collectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rode.liatr.io
  resources:
  - collectors/status
  verbs:
  - get
  - patch
  - update
