{{- if $.Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rode-manager-role-{{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rode.liatr.io
  resources:
  - attesters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rode.liatr.io
  resources:
  - attesters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rode.liatr.io
  resources:
  - clusterenforcers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rode.liatr.io
  resources:
  - collectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rode.liatr.io
  resources:
  - collectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rode.liatr.io
  resources:
  - enforcers
  verbs:
  - get
  - list
  - watch
{{- end }}
