{{- if $.Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rode-manager-rolebinding-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rode-manager-role-{{ .Release.Name }}
subjects:
- kind: ServiceAccount
  name: {{ $.Values.rbac.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
{{ end }}
