apiVersion: v1
appVersion: "1.0"
description: A Helm chart for rode
name: rode
version: 0.1.0
dependencies:
  - name: grafeas
    version: 0.1.1
    condition: grafeas.enabled
  - name: localstack
    version: 0.4.0
    condition: localstack.enabled
  - name: jetstream
    version: 0.1.0
    condition: jetstream.enabled
