# Default values for rode.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafeas:
  enabled: true
  endpoint: ""
  storageType: embedded
  container:
    port: 443
  service:
    port: 443
  certificates:
    enabled: true
    name: grafeas-ssl-certs
  secret:
    enabled: false

certificates:
  name: rode-ssl-certs

secret:
  enabled: true

localstack:
  enabled: false
  debug: false

image:
  repository: "harbor.toolchain.lead.prod.liatr.io/public/rode"
  tag: ""
  pullPolicy: IfNotPresent

enforcer:
  enabled: true
  namespaceLabel: "rode.liatr.io/enforce"
  excludedNamespaces:
  - kube-system

region: us-east-1
ginMode: release
extraEnv: []

rbac:
  create: true
  serviceAccountName: rode
  serviceAccountAnnotations: {}

container:
  port: 9443
service:
  type: ClusterIP
  port: 443

livenessProbe:
  port: 4000
  failureThreshold: 3
  initialDelaySeconds: 30
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 5

readinessProbe:
  port: 4000
  failureThreshold: 6
  initialDelaySeconds: 0
  periodSeconds: 5
  successThreshold: 1
  timeoutSeconds: 5

tolerations: []
affinity: {}
podSecurityContext: {}
podLabels: {}
nodeSelector: {}
podAnnotations: {}

replicaCount: 1
minAvailable: 1

resources: 
  limits:
    cpu: 1
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 20Mi

ingress:
  enabled: false
