# permissions to do edit enforcers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enforcer-editor-role
rules:
- apiGroups:
  - rode.liatr.io
  resources:
  - enforcers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rode.liatr.io
  resources:
  - enforcers/status
  verbs:
  - get
  - patch
  - update
