# permissions to do viewer enforcers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: enforcer-viewer-role
rules:
- apiGroups:
  - rode.liatr.io
  resources:
  - enforcers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - rode.liatr.io
  resources:
  - enforcers/status
  verbs:
  - get
