name: Skaffold
description: Publish image 
branding:
  icon: upload-cloud
  color: blue
runs:
  using: 'docker'
  image: 'Dockerfile'

inputs:
  repository:
    description: The URL for helm registry
  username:
    description: The username for accessing helm registry
  password:
    description: The password for accessing helm registry
