apiVersion: v1
kind: Pod
metadata:
  name: rode-positive
  namespace: test
spec:
  containers:
    - name: web
      image: nginx:latest
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: rode-negative
  namespace: test
spec:
  containers:
    - name: web
      image: nginx:1.18
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
              