apiVersion: rode.liatr.io/v1alpha1
kind: Collector
metadata:
  name: test-collector
  namespace: rode
spec:
  type: test
---
apiVersion: rode.liatr.io/v1alpha1
kind: Attester
metadata:
  name: testattester
  namespace: rode
spec:
  pgpSecret: testattester
  policy: |
    package test

    violation[{"msg":"analysis failed"}]{
        input.occurrences[_].discovered.discovered.analysisStatus != "FINISHED_SUCCESS"
    }
---
apiVersion: rode.liatr.io/v1alpha1
kind: ClusterEnforcer
metadata:
  name: test-enforcer
spec:
  attesters:
  - namespace: rode
    name: testattester
