name: tag
on: 
  push:
    branches:
    - actions
    #tags:
    #- 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/workflows/publish
