name: tag
on: 
  push:
    branches:
    - acr
    #tags:
    #- 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: git fetch origin +refs/tags/*:refs/tags/*
    - uses: ./.github/workflows/skaffold
      with:
        registry: liatrio.azurecr.io
        username: ${{secrets.ACR_PRINCIPAL_ID}}
        password: ${{secrets.ACR_PRINCIPAL_PASSWORD}}
    - uses: ./.github/workflows/helm
      with:
        registry: liatrio.azurecr.io
        username: ${{secrets.ACR_PRINCIPAL_ID}}
        password: ${{secrets.ACR_PRINCIPAL_PASSWORD}}
