name: tag
on: 
  push:
    branches:
    - acr
    #tags:
    #- 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - run: git fetch origin +refs/tags/*:refs/tags/*
    - uses: ./.github/workflows/skaffold
      with:
        registry: harbor.toolchain.lead.prod.liatr.io/public
        username: ${{secrets.HARBOR_USERNAME}}
        password: ${{secrets.HARBOR_PASSWORD}}
    - uses: ./.github/workflows/helm
      with:
        repository: https://harbor.toolchain.lead.prod.liatr.io/chartrepo/public
        username: ${{secrets.HARBOR_USERNAME}}
        password: ${{secrets.HARBOR_PASSWORD}}
